"""Agent implementations for Module 3."""

from __future__ import annotations

from pathlib import Path

from src.agent_platform.notebook_utils import (
    build_customer_name_notebook,
    extract_code_cells,
    notebook_to_json,
    write_module_from_code,
    write_notebook,
)
from src.agent_platform.schemas import AgentState, LLMClient
from src.agent_platform.validation import (
    build_untrusted_input_block,
    review_code_and_tests,
)


class MockLLMClient:
    """Deterministic local stand-in for an LLM provider.

    This keeps the project runnable in interviews without API keys while preserving
    the same agent boundary that a real LLM adapter would use.
    """

    def generate(self, prompt: str) -> str:
        """Return a deterministic response for traceability."""
        return f"Mock response for prompt length={len(prompt)}"


def load_prompt(path: Path) -> str:
    """Load a versioned prompt template from disk."""
    return path.read_text(encoding="utf-8")


class DeveloperAgent:
    """Generate or revise a structured Jupyter Notebook."""

    def __init__(self, llm: LLMClient, prompt_path: Path) -> None:
        self.llm = llm
        self.prompt_path = prompt_path

    def run(self, state: AgentState) -> AgentState:
        """Generate notebook JSON and extracted code."""
        task = state["task"]
        reviewer_feedback = state.get("reviewer_feedback", "")
        prompt = load_prompt(self.prompt_path)
        safe_task_block, injection_findings = build_untrusted_input_block(task)
        _ = self.llm.generate(
            f"{prompt}\n\nTASK_DATA:\n{safe_task_block}\n\n"
            f"REVIEWER_FEEDBACK:\n{reviewer_feedback}"
        )

        notebook = build_customer_name_notebook(task, reviewer_feedback)
        notebook_json = notebook_to_json(notebook)
        extracted_code = extract_code_cells(notebook_json)
        output_dir = Path(state.get("output_dir", "outputs"))

        write_notebook(notebook_json, output_dir / "developer_notebook.ipynb")
        write_module_from_code(extracted_code, output_dir / "generated_module.py")

        return {
            **state,
            "notebook_json": notebook_json,
            "extracted_code": extracted_code,
            "revision_count": state.get("revision_count", 0),
            "prompt_injection_findings": injection_findings,
        }


class TesterAgent:
    """Generate pytest tests from extracted notebook code."""

    def __init__(self, llm: LLMClient, prompt_path: Path) -> None:
        self.llm = llm
        self.prompt_path = prompt_path

    def run(self, state: AgentState) -> AgentState:
        """Create a pytest file for the generated module."""
        prompt = load_prompt(self.prompt_path)
        _ = self.llm.generate(f"{prompt}\n\nCODE_CELLS:\n{state['extracted_code']}")

        test_file = '''"""Tests generated by the Tester Agent.

Test Strategy:
- Happy path: regular messy names are normalized.
- Edge cases: empty and whitespace-only names return an empty string.
- Negative cases: non-string inputs raise TypeError.
"""

import pytest

from outputs.generated_module import normalize_customer_name


def test_normalize_customer_name_happy_path() -> None:
    assert normalize_customer_name("  jane   DOE ") == "Jane Doe"
    assert normalize_customer_name("ACME     corporation") == "Acme Corporation"


def test_normalize_customer_name_empty_or_whitespace() -> None:
    assert normalize_customer_name("") == ""
    assert normalize_customer_name("     ") == ""
    assert normalize_customer_name("\\t\\n") == ""


@pytest.mark.parametrize("bad_value", [None, 123, 3.14, ["Jane"]])
def test_normalize_customer_name_rejects_non_strings(bad_value: object) -> None:
    with pytest.raises(TypeError, match="Customer name must be a string"):
        normalize_customer_name(bad_value)
'''
        output_dir = Path(state.get("output_dir", "outputs"))
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "test_generated_module.py").write_text(test_file, encoding="utf-8")
        return {**state, "test_file": test_file}


class ReviewerAgent:
    """Review generated code and tests before commit."""

    def __init__(self, llm: LLMClient, prompt_path: Path) -> None:
        self.llm = llm
        self.prompt_path = prompt_path

    def run(self, state: AgentState) -> AgentState:
        """Produce a review report and final gate verdict."""
        prompt = load_prompt(self.prompt_path)
        _ = self.llm.generate(
            f"{prompt}\n\nCODE:\n{state['extracted_code']}\n\nTESTS:\n{state['test_file']}"
        )
        report, verdict = review_code_and_tests(
            state["extracted_code"],
            state["test_file"],
            state.get("prompt_injection_findings", []),
        )
        output_dir = Path(state.get("output_dir", "outputs"))
        output_dir.mkdir(parents=True, exist_ok=True)
        (output_dir / "review_report.md").write_text(report, encoding="utf-8")
        return {
            **state,
            "review_report": report,
            "verdict": verdict,
            "reviewer_feedback": report if verdict == "CHANGES_REQUESTED" else "",
        }
