"""Tests generated by the Tester Agent.

Test Strategy:
- Happy path: regular messy names are normalized.
- Edge cases: empty and whitespace-only names return an empty string.
- Negative cases: non-string inputs raise TypeError.
"""

import pytest

from outputs.generated_module import normalize_customer_name


def test_normalize_customer_name_happy_path() -> None:
    assert normalize_customer_name("  jane   DOE ") == "Jane Doe"
    assert normalize_customer_name("ACME     corporation") == "Acme Corporation"


def test_normalize_customer_name_empty_or_whitespace() -> None:
    assert normalize_customer_name("") == ""
    assert normalize_customer_name("     ") == ""
    assert normalize_customer_name("\t\n") == ""


@pytest.mark.parametrize("bad_value", [None, 123, 3.14, ["Jane"]])
def test_normalize_customer_name_rejects_non_strings(bad_value: object) -> None:
    with pytest.raises(TypeError, match="Customer name must be a string"):
        normalize_customer_name(bad_value)
